name: Weekly Data Collection

on:
  schedule:
    # 每周三上午11点运行 (UTC+8)
    - cron: '0 3 * * 3'  # UTC时间，对应北京时间11点
  workflow_dispatch:  # 允许手动触发

# 添加工作流权限
permissions:
  contents: write
  pull-requests: write

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data collection scripts
      run: |
        cd scripts
        python run_collection.py
        mv 汽车销量数据*.csv ../
      env:
        PYTHONPATH: ${{ github.workspace }}
      continue-on-error: true
    
    - name: Check for changes
      id: check_changes
      run: |
        git status
        echo "has_changes=$(git status --porcelain | grep -q .; echo $?)" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.has_changes == '0'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # 添加所有更改的文件
        git add -A
        
        # 提交更改
        git commit -m "自动数据更新: $(date +'%Y-%m-%d %H:%M:%S')"
        
        # 尝试拉取最新更改并重新应用本地更改
        git pull --rebase origin main
        
        # 推送更改
        git push origin main 