name: Weekly Data Collection

on:
  schedule:
    # 每周三上午11点运行 (UTC+8)
    - cron: '0 3 * * 3'  # UTC时间，对应北京时间11点
  workflow_dispatch:  # 允许手动触发

# 添加工作流权限
permissions:
  contents: write
  pull-requests: write

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests>=2.31.0 pandas>=2.0.0 python-dotenv>=1.0.0 tqdm>=4.66.0 numpy>=1.24.0 streamlit==1.31.1 plotly==5.19.0 openpyxl==3.1.2 altair==4.2.2
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run data collection scripts
      run: |
        python scripts/run_collection.py
      continue-on-error: true
    
    - name: Check for changes
      id: check_changes
      run: |
        git status
        echo "has_changes=$(git status --porcelain | grep -q .; echo $?)" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.has_changes == '0'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # 添加所有CSV文件和data目录
        git add data/ || true
        git add "*.csv" || true
        
        # 提交更改
        git commit -m "自动数据更新: $(date +'%Y-%m-%d %H:%M:%S')"
        
        # 推送更改
        git push origin HEAD:main 