name: Weekly Data Collection

on:
  schedule:
    # 每周三上午11点运行 (UTC+8)
    - cron: '0 3 * * 3'  # UTC时间，对应北京时间11点
  workflow_dispatch:  # 允许手动触发

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests>=2.31.0 pandas>=2.0.0 python-dotenv>=1.0.0 tqdm>=4.66.0 numpy>=1.24.0 streamlit==1.31.1 plotly==5.19.0 openpyxl==3.1.2 altair==4.2.2
    
    - name: Run data collection scripts
      run: |
        # 创建数据目录
        mkdir -p data
        # 运行数据采集脚本
        python scripts/run_collection.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git add *.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto data collection update $(date +'%Y-%m-%d')" && git push) 